//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv
    {
        public string Name { get; set; }
        public string Number { get; set; }
        public string Percent { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<decimal> Sum_percent { get; set; }
        public string Office { get; set; }
        public int Id { get; set; }
    }
}
